language: scala
jdk:
- oraclejdk7
sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package; project benchmark;
  test:compile; project example; test; assembly' && ci/sbt-deploy.sh && ci/sbt-gh-pages-ssh.sh
after_script:
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1befda9a908413f84c55
    - https://webhooks.gitter.im/e/a803046bf00a8b62a326
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
    secure: INxboouYQvs8qR05L6lg3ww3p63XkCuIryRoJSTsbJSybwvI4/Q+CoQRp3f5itiizjdSASjFIuE75//ZhRRzcXYTDwg+ohY1j6IjL/srrfuQE57tUtlmbJDcicktQwMZ4hCSuNBWTeUCzsECcZXWwQ7A0NY7UssZH1FSDDVitxA=
before_install:
- openssl aes-256-cbc -K $encrypted_680e980041ef_key -iv $encrypted_680e980041ef_iv
  -in .travis/deploy-key.enc -out .travis/deploy-key.pem -d
