language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package; assembly'
- ci/sbt-deploy.sh
after_script:
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1befda9a908413f84c55
    - https://webhooks.gitter.im/e/a803046bf00a8b62a326
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
    secure: KidUp6Mfj/fcSAPNKRoUMuwUGANXWaljVTPfKrLDORVDE1YYG9m+u2GQa6xirhGkNi1ZGljm844CxlmAYyUEioKY9/XTgt8wJwc0df8fE6MY1GVx5vdi4++tm0mgfyvRqPGO3JuQ8QtHiWb+/QiBC88ZfV9W2YfgbYHj7ZY3GU0=
